import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const chpFire = localFont({
  weight: "400",
  src: "../fonts/chp-fire.ttf",
  variable: "--font-chpfire",
});

export const metadata: Metadata = {
  title: "TATECHAD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chpFire.variable}`}>
        {children}
      </body>
    </html>
  );
}
